name: Hello world
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Escrever hello world no terminal
        run: echo "Hello world!"