name: Hello world
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
  schedule:
    - cron: "30 19 * * 3"
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Escrever hello world no terminal
        run: echo "Hello world!"