name: Hello world
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  # schedule:
    # - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: 18
          maven-version: 3.9.5

      - name: Execute e2e tests
        run: mvn clean install

